services:
  nextjs:
    container_name: nextjs-app
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
  app-db:
    image: mysql:8
    command:
      --collation-server=utf8mb4_0900_bin
      --transaction-isolation=READ-COMMITTED
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      TZ: Asita/Tokyo
    ports:
      - 53306:3306
