services:
  app-db:
    image: mysql:8
    command:
      --collation-server=utf8mb4_0900_bin
      --transaction-isolation=READ-COMMITTED
    restart: always
    volumes:
      - ./db/data:/var/lib/mysql
    environment:
      MYSQL_USER: root
      MYSQL_DATABASE: app
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      TZ: Asita/Tokyo
    ports:
      - 53306:3306
  nextjs:
    container_name: nextjs-app
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/:/usr/src/frontend
      - /usr/src/frontend/node_modules
    environment:
      - NODE_ENV=development
  django:
    container_name: django-app
    depends_on:
      - app-db
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/:/usr/src/backend
    environment:
      - DJANGO_ENV=development
    extra_hosts:
    - host.docker.internal:host-gateway
