services:
  db:
    image: mysql:8.0
    platform: linux/amd64
    container_name: mysql-container
    ports:
      - 3306:3306
    volumes:
      - mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=database
      - MYSQL_ROOT_PASSWORD=password
  volumes:
    mysql:
